### ISSUE TITLE
Does not launch for @brunocastello

### ISSUE THREAD

**Issue by rhaleblian** [insanemal/86box_manager_py#10]
![173975641-7359f498-accf-4510-b409-fd360ae38ccd](https://user-images.githubusercontent.com/94912/174125791-18390133-bbc9-4037-9c2f-ec8e2c645f27.png)

**Comment by rhaleblian** [comment]
@insanemal said:

OK that's odd. It's not building the path correctly. Gimme a bit and I'll get some debugging added so I can figure out where it's going bang

**Comment by insanemal** [comment]
Thanks for that. I didn't actually mean to repoen the old issue.  But that will teach me for using my phone..

**Comment by brunocastello** [comment]
I should have opened a new issue for that last night, but thanks @rhaleblian for helping out

**Comment by rhaleblian** [comment]
No worries peoples!

**Comment by brunocastello** [comment]
Hi, coming back to check the news :P

**Comment by rhaleblian** [comment]
My source does not have a line 35.

@brunocastello when you run `git log` in the repo directory what do you get?  eg

```
commit 8ba35ee51a1c4824cb7f7e4a35a007cedd676801 (HEAD -> main, origin/main, origin/HEAD)
Merge: f6dbe9f f162c57
Author: Insanemal <insanemal@gmail.com>
Date:   Mon Apr 11 07:10:25 2022 -0700

    Merge pull request #5 from insanemal/insanemal_bugs
    
    Fixed up edit dialog.
```

**Comment by insanemal** [comment]
My apologies I've been busy with work and life... buying a house adjusts
your free time spend considerably.

I'll get to these tickets this week

**Comment by brunocastello** [comment]
@insanemal Don't worry, take your time :)

**Comment by rhaleblian** [comment]
I think by now this issue is done or obsolete.  Will close this week.
