### ISSUE TITLE
UnboundLocalError: local variable 'saveConfig' referenced before assignment

### ISSUE THREAD

**Issue by telanus** [insanemal/86box_manager_py#2]
When importing a VM into 86BoxManager and got this on the terminal.

```
Traceback (most recent call last):
  File "/home/txxxs/src/86Box1/86box_manager_py/src/addvm.py", line 14, in <lambda>
    self.addButton.clicked.connect(lambda: self.addButtonClick(addVM))
  File "/home/txxxs/src/86Box1/86box_manager_py/src/addvm.py", line 58, in addButtonClick
    saveConfig(self.datadict)
UnboundLocalError: local variable 'saveConfig' referenced before assignment
```

Starting it like this: python3 86BoxManager.py

System: Kubuntu 20.04 with Python 3.8.10

**Comment by sithtoast** [comment]
I get the same on my m1 macbook pro.
Python 3.9.12 on macOS 12.3.1

**Comment by insanemal** [comment]
Ahh thanks I forgot to re-test import after a refactor. I'll get that sorted shortly.

**Comment by sithtoast** [comment]
Aww I was gonna make a pull request! Too slow!

**Comment by insanemal** [comment]
You are welcome to!

**Comment by insanemal** [comment]
That should do it. Feel free to pull it and let me know if I'm horribly wrong :D
