### ISSUE TITLE
Success Report: macOS Monterey 12.3

### ISSUE THREAD

**Issue by rhaleblian** [insanemal/86box_manager_py#7]
A success report, not a bug report.
<img width="1512" alt="Screen Shot 2022-04-14 at 9 59 23 AM" src="https://user-images.githubusercontent.com/94912/163406919-433ebd56-c907-4588-95ca-7aaf71285f48.png">
Using the universal DOS test program, ROGUE.EXE.

**Comment by brunocastello** [comment]
@rhaleblian hi, how did you manage to compile it on macOS? I am looking for the same thing

**Comment by insanemal** [comment]
You don't compile it. It's python. You just run it with the python interpreter.

**Comment by rhaleblian** [comment]
So true.  IIRC you are ultimately going to run something like
```
cd src
python3 86BoxManager.py
```
But first you need Qt5 for Python installed.  Look at the Homebrew project for a way to do that.

**Comment by brunocastello** [comment]
![Screen Shot 2022-06-15 at 11 06 01 PM](https://user-images.githubusercontent.com/23453202/173975641-7359f498-accf-4510-b409-fd360ae38ccd.png)

Well, I installed PyQt5 from homebrew and after attempting to start it, I have this error.

**Comment by insanemal** [comment]
OK that's odd. It's not building the path correctly.  Gimme a bit and I'll get some debugging added so I can figure out where it's going bang

**Comment by rhaleblian** [comment]
No problem over here.  This issue should remain closed.
The above is a new issue.
